### ISSUE TITLE
Match image size, to the font size

### ISSUE THREAD

**Issue by 1alexvash** [ZxMYS/react-twemoji#44]
I'm trying to replace the standard set of emojis on my website with the twitter one

Is there an easy, way to accomplish it?
![image](https://user-images.githubusercontent.com/46556479/210601403-a4b23561-3186-4d07-8b22-4b946539921b.png)

**Comment by junhoyeo** [comment]
Came across this issue, and yes, there is! @1alexvash

1. First, add classnames to generated `img` elements using `className`:
```ts
twemoji.parse(element, {
  className: 'twemoji',
});
```

2. Add CSS with `height: 1em`.
```css
img.twemoji {
  height: 1em;
  width: auto;
  display: inline-block;
}
```
